site_name: WXDoc(Android)

nav:
  - '傲软抠图': 'index.md'
  - '全局配置': 'global.md'
  - 'User Guide':
        - 'Google Pay': 'Google Play订阅接入文档.md'
        - 'Jetpack MVVM': 'Jetpack MVVM架构浅析.md'

theme:
  name: material
  language: zh
  palette:
    - scheme: default
      primary: white
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  # font:
  #   code: Source Code Pro
  icon:
    repo: fontawesome/brands/github
  features:
    # - header.autohide
    - navigation.expand
    - navigation.instant
    # - navigation.tabs
    # - navigation.sections
    - navigation.top
    # - toc.integrate

copyright: Copyright &copy; 2020 - 2021 WangXu Tech
edit_uri: ""

extra:
  generator: false

repo_url: https://github.com/sqsong66/WXDoc.git
repo_name: Github

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/sqsong66
#       name: Github

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic:
      mode: view
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

# plugins:
#   - tags
#   - git-revision-date-localized
